// Code generated by packages/dto/scripts/generate-go-sse-events.ts. DO NOT EDIT.
//
// Источник правды: packages/dto/src/realtime/sse-event.dto.ts (ADR-004:86).
// Правка вручную затрётся следующим запуском генератора, а CI-проверка
// актуальности файла упадёт на расхождении.

package sse

// EventType — имя кадра в глобальном SSE-потоке уведомлений.
type EventType string

const (
	// EventNotificationNew содержит новое персональное уведомление пользователя.
	EventNotificationNew EventType = "notification.new"

	// EventNotificationBadge содержит обновление счётчика непрочитанных.
	EventNotificationBadge EventType = "notification.badge"

	// EventSessionInvited содержит приглашение пользователя на собеседование.
	EventSessionInvited EventType = "session.invited"

	// EventCodeRunnerStatus содержит статус асинхронного прогона автотестов кандидата.
	EventCodeRunnerStatus EventType = "code_runner.status"

	// EventAIReportReady содержит уведомление о готовности AI-отчёта интервью.
	EventAIReportReady EventType = "ai.report_ready"

	// EventAccountUpdated содержит изменение баланса кредитов или тарифного плана.
	EventAccountUpdated EventType = "account.updated"

	// EventSystemBroadcast содержит общесистемный алерт или анонс технических работ.
	EventSystemBroadcast EventType = "system.broadcast"

	// EventAuthRevoked отправляется последним кадром перед разрывом потока при отзыве авторизации.
	EventAuthRevoked EventType = "auth.revoked"
)

// Severity — визуальная severity уведомления для отрисовки.
//
// Отдельная от NotificationType сущность: NotificationType остаётся
// доменным перечислением из БД (SYSTEM | INTERVIEW | MESSAGE) и приходит в
// payload в поле category, тогда как severity описывает вид уведомления и
// приходит в поле severity (ADR-004:87).
type Severity string

const (
	SeverityInfo    Severity = "info"
	SeveritySuccess Severity = "success"
	SeverityWarning Severity = "warning"
	SeverityError   Severity = "error"
)
